apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms
  labels:
    app: notification-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ms
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      containers:
        - name: notification-ms
          image: islamahmad/eaproj-notficationms:1.0.11
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-notficationms:1.0.11"

            # GENERAL
            - name: SERVER_PORT
              value: "8080"

            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-ms-secrets
                  key: MAIL_PASSWORD

          envFrom:
            - configMapRef:
                name: notification-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
